import Head from 'next/head'
import { PostList } from 'src/components/Post/PostList'

const PostsId =() => {

  return (
    <div>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PostList/>
    </div>
  )
}

export default PostsId