import Head from 'next/head'
import { Header } from 'src/components/Header'
import { User } from 'src/components/User';

const UserId = () => {

    return (
      <div>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header/>
  
        <User/>
      </div>
    )
  }

  export default UserId