import Head from 'next/head'
import { Header } from 'src/components/Header'
import { Post } from 'src/components/Post';



const PostId = () => {

    return (
      <div className={styles.container}>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header/>
  
        <Post/>
      </div>
    )
  }

  export default PostId
  