import Head from 'next/head'
import { PostDetail } from 'src/components/Post/PostDetail';



const PostId = () => {

    return (
      <div>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <PostDetail/>
      </div>
    )
  }

  export default PostId
  