import Head from 'next/head'
import { Footer } from 'src/components/Footer'
import { Header } from 'src/components/Header'
import { Main } from 'src/components/Main'
import styles from 'src/styles/Home.module.css'






export default function Home(props) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header className={styles.header}/>

      {props.isShow ? <h1>{props.doubleCount}</h1> : null}
      <button href='/about' onClick={props.handleClick}>
        ボタン
      </button>
      <button onClick={props.showChange}>
        {props.isShow ? "非表示" : "表示"}
      </button>

      <input 
        type="text"
        value={props.text}
        onChange={props.textInput}
      />
      <button onClick={props.handleAdd}>追加</button>
      <ul>
        {props.array.map(item => {
          return (
          <li key={item}>{item}</li>
          )
        })}
      </ul>

      <Main page="index"/>

      <Footer/>

    </div>
  )
}
