import Head from 'next/head'
import { useRouter } from 'next/router'
import { Header } from 'src/components/Header'
import styles from 'src/styles/Home.module.css'


export default function Home(props) {
    const router = useRouter()
    const id = router.query.id

    return (
      <div className={styles.container}>
        <Head>
          <title>Index</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header className={styles.header}/>
  
        <div>{id}</div>
      </div>
    )
  }