import Head from 'next/head'
import { Header } from 'src/components/Header'
import { Comment } from 'src/components/Comment';



const CommentId = () => {

    return (
      <div>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header/>
  
        <Comment/>
      </div>
    )
  }

  export default CommentId