import Head from 'next/head'
import { Header } from 'src/components/Header'
import { Comments as CommentsComponent } from 'src/components/Comments'
import { SWRConfig } from 'swr';

export const getStaticProps = async (ctx) => {
  const { id } = ctx.query;
  // ユーザー一覧の取得
  const COMMENTS_API_URL = `https://jsonplaceholder.typicode.com/comments`;
  const comments = await fetch(COMMENTS_API_URL)
  const commentsData = await comments.json();
  return {
    props: {
      fallback: {
        [COMMENTS_API_URL]: commentsData,
      }
    },
  }
};

const CommentsId =(props) => {
  const { fallback } = props

  return (
    <div>
      <Head>
        <title>Comment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SWRConfig value={{ fallback }}>
        <Header/>

        <CommentsComponent/>
      </SWRConfig>

    </div>
  )
}

export default CommentsId